### ISSUE TITLE
Spacing Beetwen Radio Button

### ISSUE THREAD

**Issue by muslimmuda15** [babincc/flutter_workshop#18]
How to add spacing between radio button when orientation is veertical?

**Comment by babincc** [comment]
I have just published a new update (version 3.2.0), which allows for custom vertical spacing.

Just use the `spacing` parameter in the `RadioGroupDecoration` which goes in the `RadioGroup`'s `decoration` field.

```dart
RadioGroup(
  controller: myController,
  values: myValues,
  decoration: const RadioGroupDecoration(
      spacing: 10.0, // This value here
  ),
)
```
