### ISSUE TITLE
Color calculators

### ISSUE THREAD

**Issue by babincc** [babincc/flutter_workshop#2]
Add color calculators/converters

- [x] xy to:
     - [x] RGB
     - [x] HSV
     - [x] Hex
     - [x] HSL
     - [x] Flutter Color object
     - [x] int
- [x] RGB to:
     - [x] xy
     - [x] HSV
     - [x] Hex
     - [x] HSL
     - [x] Flutter Color object
     - [x] int
- [x] HSV to:
     - [x] xy
     - [x] RGB
     - [x] Hex
     - [x] HSL
     - [x] Flutter Color object
     - [x] int
- [x] Hex to:
     - [x] xy
     - [x] RGB
     - [x] HSV
     - [x] HSL
     - [x] Flutter Color object
     - [x] int
- [x] HSL to:
     - [x] xy
     - [x] RGB
     - [x] HSV
     - [x] Hex
     - [x] Flutter Color object
     - [x] int
- [x] Flutter color object to:
     - [x] xy
     - [x] RGB
     - [x] HSV
     - [x] Hex
     - [x] HSL
     - [x] int
- [x] int to:
     - [x] xy
     - [x] RGB
     - [x] HSV
     - [x] Hex
     - [x] HSL
     - [x] Flutter Color object

**Comment by babincc** [comment]
Added in 1.1.0 update

**Comment by babincc** [comment]
Examples:

```dart
ColorConverter.xy2rgb(0.5, 0.5); // [255, 222, 0]
ColorConverter.rgb2hsl(255, 0, 0); // [0.0, 1.0, 0.5]
ColorConverter.hsv2hex(0, 1.0 , 1.0); // "ffff0000"
ColorConverter.color2hsv(Color(0xffff0000)); // [0.0, 1.0, 1.0]
ColorConverter.int2rgb(4286611584); // [128, 128, 128]
```

Also can be used as an extension of Flutter's `Color` object

```dart
Color myColor = Color(0xff8a4888);

myColor.toXy(); // [0.3209554122773742, 0.21993715851681886, 0.1181557673818057]
myColor.toRgb(); // [138, 72, 136]
myColor.toHex(); // "ff8a4888"
myColor.toInt(); // 4287252616
```

**Comment by esDotDev** [comment]
It would be nice if we could go directly from Flutter Color to `ColorXY`. Something like:
```dart
final white = ColorXy.fromColor(Colors.white.withOpacity(.5));
final off = ColorXy.fromColor(Colors.transparent);
```

**Comment by babincc** [comment]
Thanks for bringing this up! I have added it with the latest commit [9d7fd88](https://github.com/babincc/flutter_workshop/commit/9d7fd882c416cc16853b2bb38c6d765713b16b57)!
