### ISSUE TITLE
Add ability to get BridgeID when calling discoverBridges

### ISSUE THREAD

**Issue by esDotDev** [babincc/flutter_workshop#20]
In other apps we see an ID when connecting to new Bridges, but this discoverBridges only returns a list of IP addresses.
![image](https://github.com/babincc/flutter_workshop/assets/736973/ea123869-2126-425a-8254-8a49590aa520)

Is there any way we can get this ID, or can you add support for it?

**Comment by babincc** [comment]
I think I will be able to add this functionality; however, I just left for vacation and won't be back for a week and a half. I don't have any Hue products with me to run tests on; so, I cannot work on a core feature like this until I get back.

**Comment by babincc** [comment]
I have published `2.0.0-beta.4` to pub.dev. 

Developers now will have access to an abbreviated `bridgeId`, like the one in the screenshot in the original question, as well as the IP address.
